language: php

php:
  - 7.2
  - 7.4

sudo: false

git:
  depth: 1

env:
  matrix:
    - PHALCON_VERSION="v4.0.0"

before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install psr < /dev/null &)

install:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon -b {$PHALCON_VERSION}
  - (cd cphalcon/build; ./install)
  - phpenv config-add cphalcon/tests/_ci/phalcon.ini

script:
  - cd ../../Phalcon-Config && composer update && ./vendor/bin/phpunit
