language: php

php:
  - 7
  - 7.1

sudo: false

before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install psr < /dev/null &)
  
script:
  - git clone https://github.com/phalcon/cphalcon && cd cphalcon && git checkout tags/v4.0.0 ./ && cd build && ./install
  - cd ../../Phalcon-Config && composer update && ./vendor/bin/phpunit
