name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: cd Phalcon-Config && composer install --prefer-dist --no-progress && cd ../Phalcon-Container-Builder && composer install --prefer-dist --no-progress

    - name: Install phalcon
      uses: shivammathur/setup-php@2.29.0
      with:
        php-version: 8.3
        extensions: mbstring, yaml, psr, phalcon5
      run: cd Phalcon-Config && ./vendor/bin/phpunit && cd ../Phalcon-Container-Builder && ./vendor/bin/phpunit
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
